[general]
import = ["~/.config/alacritty/kanagawa-wave.toml"]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
LANG = "en_US.UTF-8"

[window]
# decorations = "None"
option_as_alt = "Both"
dynamic_padding = true
startup_mode = "Maximized"

[mouse]
hide_when_typing = true

[font]
size = 20

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
