#!/usr/bin/env zsh

# `exports` is used to provide custom variables.

# --- PATH modifications ---

# GPG agent:
PATH="/usr/local/opt/gpg-agent/bin:$PATH"

# Adds `npm` binary files:
PATH="/usr/local/share/npm/bin:$PATH"

# Adds `go` binary files:
PATH="$HOME/go/bin:$PATH"

# Adds `cargo` binary files:
PATH="$HOME/.cargo/bin:$PATH"

# --- macOS specific settings ---
if [[ "$(uname)" == "Darwin" ]]; then
	# This is required because `openssl` is keg-only in `brew`,
	export LDFLAGS="-L$(brew --prefix)/opt/openssl/lib"
	export CPPFLAGS="-I$(brew --prefix)/opt/openssl/include"
	export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
	export PKG_CONFIG_PATH="$(brew --prefix)/opt/openssl/lib/pkgconfig"

	# Java setup:
	if [[ -d "/opt/homebrew/opt/openjdk" ]]; then
		export JAVA_HOME="/opt/homebrew/opt/openjdk"
		PATH="$JAVA_HOME/bin:$PATH"
	elif /usr/libexec/java_home &>/dev/null; then
		export JAVA_HOME=$(/usr/libexec/java_home)
		PATH="$JAVA_HOME/bin:$PATH"
	else
		echo "Warning: No Java Runtime found."
	fi
fi

# --- General ---

# Editor:
export EDITOR="$(which nvim)"

# GPG:
export GPG_TTY="$(tty)" # for pinentry

# Homebrew:
export HOMEBREW_NO_ANALYTICS=1 # disables statistics that brew collects

export PATH
