#!/usr/bin/env zsh

# `external` handles all complex external tools.

if [[ ! "$PATH" == */opt/fzf/bin* ]]; then
	export PATH="$PATH:$(brew --prefix)/opt/fzf/bin"
	eval "$(fzf --zsh)"
fi

# Using `fd` for imporved file and directory search
export FZF_DEFAULT_COMMAND='fd --hidden --strip-cwd-prefix --exclude .git'
export FZF_CTRL_T_COMMAND='fd --hidden --strip-cwd-prefix --exclude .git'
export FZF_ALT_C_COMMAND='fd --type=d --hidden --strip-cwd-prefix --exclude .git'

export FZF_DEFAULT_OPTS='--layout=reverse-list --bind "ctrl-a:toggle" --bind "ctrl-h:change-preview-window(hidden|)" --cycle -i'
export FZF_CTRL_T_OPTS='--preview "_fzf_complete_realpath {}"'
export FZF_ALT_C_OPTS='--preview "_fzf_complete_realpath {}"'
export FZF_CTRL_R_OPTS='--reverse'

# `zoxide` has an option to use `fzf` to provide completions natively,
# but it works only for `z NAME<SPACE><TAB>`,
# it does not work for `z NAME<TAB>`.
eval "$(zoxide init zsh --no-cmd)"

z() {
	# I need this function to setup custom code completion for `zoxide`.
	\__zoxide_z "$@"
}
