#!/usr/bin/env bash

set -e

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ARGS=("$@")

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

run_dotbot() {
	local config
	config="$1"

	"$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
		-d "$BASEDIR" \
        --plugin-dir dotbot-brewfile \
		-c "$config" "${ARGS[@]}"
}

dotbot_configs=(
    "steps/terminal.yaml"
	"steps/dependencies.yaml"
	"steps/vscode.yaml"
)

for config in "${dotbot_configs[@]}"; do
	run_dotbot "$config"
done
