#!/usr/bin/env bash

set -e

SHELL="/bin/bash"
export SHELL

readonly DOTBOT_DIR="dotbot"
readonly DOTBOT_BIN="bin/dotbot"
readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly ARGS="$@"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

run_dotbot() {
  local config="$1"

  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "$BASEDIR" \
    -c "$config" $ARGS
}

setup_files=(
  "setup/zsh.yaml"
)

for file in "${setup_files[@]}"; do
  run_dotbot "$file"
done
